# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: master-deploy
  cancel-in-progress: true

permissions:
  contents: read
  # these permissions are required for the deploy-pages action to work properly
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    environment:
      # links this workflow to the deployments page on your repository
      name: github-pages
      # attaches the deployed URL to this job on the workflow summary
      url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cocos Creator Build
        # You may pin to the exact commit or the version.
        # uses: miggene/cocos-build@67570229062ebf4ed87c70fc0a2885319e7a7256
        uses: miggene/cocos-build@v1.2.3
        with:
          # cocos creator download urls
          # cocos_download_url: # optional, default is https://creator-api.cocos.com/api/cocoshub/editor_version_list?lang=zh
          # cocos creator version
          cocos_version: 3.8.3 # optional, default is 0.0.0
          # cocos creator type(2d/3d)
          cocos_type: 3d # optional, default is 2d
          # project path for build
          # project_path: # optional, default is ./
          # platform to build
          platform: web-mobile # optional, default is web-mobile
          # build path
          # build_path: # optional, default is ./build

      - name: Create Archive
        run: |
          cd build/web-mobile
          tar --dereference --hard-dereference -cf ../dist.tar .

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist.tar
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1